### ISSUE TITLE
Result value seems to be included at the test step as a comment

### ISSUE THREAD

**Issue by fadihawli** [testpointcorp/Vansah-API-Binding-Java#1]
For a test case which has steps it seems the result value is being included against the test step. 

![image](https://user-images.githubusercontent.com/8530749/102138142-fffe8000-3eaf-11eb-9cda-dc9f0a47f026.png)

the Result should only be added against the step row and our comments will appear against the log

**Comment by tp-Fernando** [comment]
hi Fadi Hawli, those numbers you see in the comments in test logs were purposely sent by me as part of some tests I was doing. I put numbers to differentiate the tests I was doing. They are not result value.
