### ISSUE TITLE
Test script steps are missing from a test log

### ISSUE THREAD

**Issue by fadihawli** [testpointcorp/Vansah-API-Binding-Java#3]
@vascubrian  it seems that when we pass the test step identifier to a test case only the step related to the identifier is being added against the test log report.

the issue is the actual test case has other test steps which are not reflected in the test log report.

example, Test Case # 127 has 3 steps
![image](https://user-images.githubusercontent.com/8530749/102151750-a1dd9700-3ec7-11eb-8e96-f8f2375871d9.png)

when we send a result against the test case (step id#1) it displays the test log as completed and doesnt include the other steps i.e(2 and 3)

![image](https://user-images.githubusercontent.com/8530749/102151860-e6693280-3ec7-11eb-8ddc-cc97d2ef6735.png)

**Expected Behaviour**

Display the full test script in the log report

**Comment by vascubrian** [comment]
Sure Let me address it @fadihawli

**Comment by tp-Fernando** [comment]
I tested and the issue is fixed. The logs are being kept for all steps, not only for the step which was tested as it was happening before. Looks good now.
![image](https://user-images.githubusercontent.com/30623282/102420895-480bd700-4057-11eb-94a9-2b75335e5119.png)
