### ISSUE TITLE
There are two Host.java files in the repo

### ISSUE THREAD

**Issue by MarkMaMsw** [testpointcorp/Vansah-API-Binding-Java#7]
Hi @tp-Fernando @fadihawli 

When I was viewing the project code, I find that the 2 files below are basically the same.
> src/test/java/testpoint/Host.java 
> src/test/java/Host.java 

Maybe it would be better to remove the earlier version(the one under src/test/java/ has less code).

**Comment by fadihawli** [comment]
they should be removed from V1 as they are no-longer supported. thanks @MarkMaMsw
