### ISSUE TITLE
Enrich REDADME.md file to help people have better understanding of the project.

### ISSUE THREAD

**Issue by MarkMaMsw** [testpointcorp/Vansah-API-Binding-Java#8]
For people like me who read code the first time, it will be a little bit confusing about which file to start with.

So I think maybe it will be a good idea to add more details to our README file. For example, as many other GitHub open source projects do, we can have an introduction to our project, and we can also have a "how to install/use" module along with our documentation link.

**Comment by fadihawli** [comment]
@MarkMaMsw  looks like you have voted to manage this task :)
